# Generated by Django 3.0.4 on 2020-03-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('docking_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('protein_type', models.CharField(max_length=20)),
                ('popular_views', models.DecimalField(decimal_places=1, max_digits=10)),
                ('drug_source', models.CharField(max_length=50)),
            ],
        ),
    ]
