# Generated by Django 3.0.4 on 2020-03-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='drug_synonyms',
            field=models.TextField(default=''),
        ),
    ]
