# Generated by Django 3.0.4 on 2020-03-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_score_drug_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='popular_views',
            field=models.IntegerField(),
        ),
    ]
