# Generated by Django 3.0.4 on 2020-03-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200319_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='cid',
            field=models.IntegerField(default=0),
        ),
    ]
