# Generated by Django 3.0.4 on 2020-03-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_score_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='drug_name',
            field=models.TextField(default=''),
        ),
    ]
