# Generated by Django 3.0.4 on 2020-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_cid2drugbankid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbank_id', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('z_score_pan', models.FloatField()),
                ('z_score_sars', models.FloatField()),
                ('z_score_mers', models.FloatField()),
                ('z_score_ibv', models.FloatField()),
                ('z_score_mhv', models.FloatField()),
                ('p_value_pan', models.FloatField()),
                ('p_value_sars', models.FloatField()),
                ('p_value_mers', models.FloatField()),
                ('p_value_mhv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GSEAScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmap_instance', models.IntegerField()),
                ('drugbank_id', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('dose', models.FloatField()),
                ('cell_line', models.TextField()),
                ('mers1_es', models.FloatField()),
                ('mers1_p', models.FloatField()),
                ('sars1_es', models.FloatField()),
                ('sars1_p', models.FloatField()),
                ('sars2_es', models.FloatField()),
                ('sars2_p', models.FloatField()),
            ],
        ),
    ]
