# Generated by Django 3.0.4 on 2020-04-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_drugscreening_gseascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugscreening',
            name='p_value_ibv',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
