# Generated by Django 3.0.4 on 2020-05-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_drugscreening_p_value_ibv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CidProteinScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('protein_type', models.CharField(max_length=20)),
                ('docking_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('drug_name', models.TextField(default='')),
                ('drug_synonyms', models.TextField(default='')),
                ('popular_views', models.IntegerField(default=0)),
                ('drug_source', models.CharField(max_length=50)),
                ('drugbank_id', models.CharField(max_length=10)),
            ],
        ),
    ]
