# Generated by Django 3.0.4 on 2020-05-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_cidproteinscore_druginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginfo',
            name='cas',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
