# Generated by Django 3.0.4 on 2020-05-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_druginfo_cas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CidProteinScore',
        ),
        migrations.DeleteModel(
            name='DrugInfo',
        ),
    ]
