# Generated by Django 3.0.4 on 2020-05-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_cidproteinscore_druginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CidProteinScore',
        ),
        migrations.DeleteModel(
            name='DrugInfo',
        ),
    ]
