# Generated by Django 3.0.4 on 2020-05-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20200515_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(db_index=True)),
                ('cas', models.CharField(default='-', max_length=20)),
                ('drug_name', models.TextField(default='')),
                ('drug_synonyms', models.TextField(default='')),
                ('popular_views', models.IntegerField(default=0)),
                ('drug_source', models.CharField(max_length=50)),
                ('drugbank_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CidProteinScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_type', models.CharField(max_length=20)),
                ('docking_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.DrugInfo')),
            ],
        ),
    ]
