# Generated by Django 3.0.4 on 2020-05-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_cidproteinscore_druginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginfo',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
