# Generated by Django 3.0.4 on 2020-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_druginfo_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHIDrugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_mark', models.CharField(max_length=4)),
                ('oral', models.CharField(max_length=20)),
                ('single_or_compound', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=18)),
                ('price_start_date', models.CharField(max_length=14)),
                ('price_end_date', models.CharField(max_length=14)),
                ('english_name', models.CharField(max_length=240)),
                ('volume', models.CharField(max_length=14)),
                ('unit', models.CharField(max_length=104)),
                ('main_ingredient_name', models.CharField(max_length=112)),
                ('main_ingredient_volume', models.CharField(max_length=24)),
                ('main_ingredient_unit', models.CharField(max_length=102)),
                ('dosage', models.CharField(max_length=172)),
                ('company_name', models.CharField(max_length=40)),
                ('category_code', models.CharField(max_length=4)),
                ('quality_category_code', models.CharField(max_length=2)),
                ('chinese_name', models.CharField(max_length=256)),
                ('category_name', models.CharField(max_length=600)),
                ('second_ingredient_name', models.CharField(max_length=112)),
                ('second_ingredient_volume', models.CharField(max_length=22)),
                ('second_ingredient_unit', models.CharField(max_length=102)),
                ('third_ingredient_name', models.CharField(max_length=112)),
                ('third_ingredient_volume', models.CharField(max_length=22)),
                ('third_ingredient_unit', models.CharField(max_length=102)),
                ('fourth_ingredient_name', models.CharField(max_length=112)),
                ('fourth_ingredient_volume', models.CharField(max_length=22)),
                ('fourth_ingredient_unit', models.CharField(max_length=102)),
                ('fifth_ingredient_name', models.CharField(max_length=112)),
                ('fifth_ingredient_volume', models.CharField(max_length=22)),
                ('fifth_ingredient_unit', models.CharField(max_length=102)),
                ('sixth_ingredient_name', models.CharField(max_length=112)),
                ('sixth_ingredient_volume', models.CharField(max_length=22)),
                ('sixth_ingredient_unit', models.CharField(max_length=102)),
                ('production_company', models.CharField(max_length=84)),
                ('atc_code', models.CharField(max_length=16)),
                ('less_than_five_year', models.CharField(max_length=2)),
            ],
        ),
    ]
