# Generated by Django 3.0.4 on 2020-05-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20200520_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_similarity_score', models.FloatField()),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugsimilarity_drug1', to='search.DrugInfo')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugsimilarity_drug2', to='search.DrugInfo')),
            ],
        ),
    ]
