# Generated by Django 3.0.4 on 2020-05-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_drugsimilarity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cid2Drugbankid',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
