# Generated by Django 3.0.4 on 2020-09-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_auto_20200624_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginfo',
            name='formal_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='heavy_atoms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='molar_refractivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='num_of_rings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='number_of_atoms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='rotatable_bonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='topological_surface_area_mapping',
            field=models.FloatField(default=0.0),
        ),
    ]
